export const ACTION_GET_STATIONS_STARTED = "GET_STATIONS_STARTED";
export const ACTION_GET_STATIONS_SUCCESS = "GET_STATIONS_SUCCESS";
export const ACTION_GET_STATIONS_FAILED = "GET_STATIONS_FAILED";

export const ACTION_GET_BRANDS_STARTED = "GET_BRANDS_STARTED";
export const ACTION_GET_BRANDS_SUCCESS = "GET_BRANDS_SUCCESS";
export const ACTION_GET_BRANDS_FAILED = "GET_BRANDS_FAILED";

export const ACTION_GET_FUELS_STARTED = "GET_FUELS_STARTED";
export const ACTION_GET_FUELS_SUCCESS = "GET_FUELS_SUCCESS";
export const ACTION_GET_FUELS_FAILED = "GET_FUELS_FAILED";