# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-02 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0002_remove_city_city_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0)),
                ('rating_counter', models.IntegerField(default=0)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city_id', models.IntegerField(default=0)),
                ('tel', models.CharField(max_length=100)),
                ('image_path', models.CharField(max_length=200)),
                ('brand_id', models.IntegerField(default=0)),
            ],
        ),
    ]
