# Generated by Django 2.1.2 on 2018-10-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0003_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_info', models.CharField(max_length=5000)),
                ('main_img_path', models.CharField(max_length=200)),
                ('member1_name', models.CharField(max_length=50)),
                ('member1_img_path', models.CharField(max_length=200)),
                ('member1_position', models.CharField(max_length=50)),
                ('member2_name', models.CharField(max_length=50)),
                ('member2_img_path', models.CharField(max_length=200)),
                ('member2_position', models.CharField(max_length=50)),
                ('member3_name', models.CharField(max_length=50)),
                ('member3_img_path', models.CharField(max_length=200)),
                ('member3_position', models.CharField(max_length=50)),
            ],
        ),
    ]
